package:
  name: conda_analysispackage
  version: 0.2.0

requirements:
  build:
    - python
  run:
    - python
    - conda
    - conda-build

# The build number should be incremented for new builds of the same version
build:            # (optional)
  number: {{environ.get('BINSTAR_BUILD', 1)}}
    
about:
  home: https://github.com/ContinuumIO/conda_analysis_package
  license: MIT License
