package:
  name: conda_analysis_package
  version: 0.2.1

requirements:
  build:
    - python
  run:
    - python
    - conda
    - conda-build

source:
  git_url: ../

# The build number should be incremented for new builds of the same version
build:            # (optional)
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: py{{environ.get('PY_VER').replace('.', '')}}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}

about:
  home: https://github.com/ContinuumIO/conda_analysis_package
  license: MIT License
